branch-defaults:
  dev:
    environment: klon-production
environment-defaults:
  klon-website:
    branch: null
    repository: null
global:
  application_name: klon
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.6
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
