# Generated by Django 2.1.3 on 2018-11-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181108_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_foods', to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_foodoptions', to='api.Food'),
        ),
    ]
