# Generated by Django 2.1.3 on 2018-11-08 08:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurant_uuid_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='open_day',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=7, null=True),
        ),
    ]
