# Generated by Django 2.1.3 on 2018-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181108_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurant_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
