# Generated by Django 2.1.3 on 2018-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_food_restaurant_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodoption',
            name='food_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
