# Generated by Django 2.1.3 on 2018-11-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_foodoption_uuid_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurant_admin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='uuid_admin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
