# Generated by Django 2.1.3 on 2018-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181116_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodoption',
            name='food_admin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodoption',
            name='uuid_admin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
